# Generated by Django 4.0.3 on 2022-10-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_mastercontents_vehicalbasicdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicalbasicdetail',
            name='Aadhar_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicalbasicdetail',
            name='model_number',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicalbasicdetail',
            name='vehical_number',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='vehicalbasicdetail',
            table='vehicalbasicdetail',
        ),
    ]
