# Generated by Django 4.1.5 on 2023-01-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_vehicalbasicdetail_aadhar_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='driveroperatorregistration',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicalname', models.CharField(max_length=200)),
                ('expriencesinyear', models.IntegerField()),
                ('driveroperatorname', models.CharField(max_length=200)),
                ('Aadhar_number', models.CharField(max_length=20)),
                ('alternet_mobilenumber', models.IntegerField()),
                ('license_number', models.CharField(max_length=50)),
                ('driver_image', models.ImageField(upload_to='user/static/Uploaded/UserProfiles/')),
                ('created_by', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'driveroperatorregistration',
            },
        ),
        migrations.CreateModel(
            name='heavyvehivalregistration',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('vehical_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('vehical_number', models.CharField(max_length=500)),
                ('manufacture_date', models.CharField(max_length=500)),
                ('ownername', models.CharField(max_length=300)),
                ('Aadhar_number', models.CharField(max_length=20)),
                ('vehicle_image', models.ImageField(upload_to='static/images/vehicles/1.jpg')),
                ('created_by', models.IntegerField()),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'heavyvehivalregistration',
            },
        ),
        migrations.CreateModel(
            name='labour_contructor',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('labourcontractorname', models.CharField(max_length=300)),
                ('labourwork', models.CharField(max_length=200)),
                ('lobourinnumber', models.CharField(max_length=12)),
                ('mobile_number', models.CharField(max_length=20)),
                ('contractorAadhar_number', models.CharField(max_length=20)),
                ('labour_image', models.ImageField(upload_to='user/static/Uploaded/UserProfiles/')),
                ('created_by', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'labour_contructor',
            },
        ),
        migrations.CreateModel(
            name='Request_driver_Operator',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicalname', models.CharField(max_length=200)),
                ('expriencesinyear', models.IntegerField()),
                ('driveroperatorname', models.CharField(max_length=200)),
                ('Aadhar_number', models.CharField(max_length=20)),
                ('alternet_mobilenumber', models.IntegerField()),
                ('license_number', models.CharField(max_length=50)),
                ('driver_image', models.FileField(blank=True, max_length=500, null=True, upload_to='')),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('tehsil', models.CharField(max_length=100)),
                ('created_by', models.IntegerField()),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'request_driver_operator',
            },
        ),
        migrations.CreateModel(
            name='Request_Heavy_Vehical',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('vehical_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('vehical_number', models.CharField(max_length=500)),
                ('ownername', models.CharField(max_length=300)),
                ('Aadhar_number', models.CharField(max_length=20)),
                ('vehicle_image', models.CharField(blank=True, max_length=255, null=True)),
                ('manufectoring_date', models.CharField(max_length=100)),
                ('created_by', models.IntegerField()),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'request_heavy_vehical',
            },
        ),
        migrations.CreateModel(
            name='Request_labour_contructor',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('labourcontractorname', models.CharField(max_length=300)),
                ('labourwork', models.CharField(max_length=200)),
                ('lobourinnumber', models.CharField(max_length=12)),
                ('mobile_number', models.CharField(max_length=20)),
                ('contractorAadhar_number', models.CharField(max_length=20)),
                ('labour_image', models.CharField(blank=True, max_length=500, null=True)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('tehsil', models.CharField(max_length=100)),
                ('created_by', models.IntegerField()),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'request_labour_contructor',
            },
        ),
        migrations.CreateModel(
            name='Request_SubContractor',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('contractorname', models.CharField(max_length=100)),
                ('firmname', models.CharField(max_length=500)),
                ('expriencesinyear', models.IntegerField()),
                ('license_number', models.CharField(max_length=50)),
                ('Aadhar_number', models.CharField(max_length=20)),
                ('subcontractor_image', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.IntegerField()),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'request_subcontractor',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('requirement_image', models.CharField(max_length=500)),
                ('created_by', models.IntegerField()),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'requirement',
            },
        ),
        migrations.CreateModel(
            name='subcontractorregistration',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('contractorname', models.CharField(max_length=100)),
                ('firmname', models.CharField(max_length=500)),
                ('expriencesinyear', models.IntegerField()),
                ('license_number', models.CharField(max_length=50)),
                ('Aadhar_number', models.CharField(max_length=20)),
                ('subcontractor_image', models.ImageField(upload_to='user/static/Uploaded/UserProfiles/')),
                ('created_by', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'subcontractorregistration',
            },
        ),
        migrations.CreateModel(
            name='VedioUplaod',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('image_uplaod', models.CharField(max_length=500)),
                ('vediourl', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vedioupload',
            },
        ),
        migrations.DeleteModel(
            name='vehicalbasicdetail',
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
    ]
