# Generated by Django 4.1.5 on 2023-01-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_driveroperatorregistration_heavyvehivalregistration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_heavy_vehical',
            old_name='manufectoring_date',
            new_name='manufacture_date',
        ),
        migrations.RemoveField(
            model_name='request_driver_operator',
            name='district',
        ),
        migrations.RemoveField(
            model_name='request_driver_operator',
            name='state',
        ),
        migrations.RemoveField(
            model_name='request_driver_operator',
            name='tehsil',
        ),
        migrations.RemoveField(
            model_name='request_labour_contructor',
            name='district',
        ),
        migrations.RemoveField(
            model_name='request_labour_contructor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='request_labour_contructor',
            name='tehsil',
        ),
    ]
