# Generated by Django 4.1.5 on 2023-02-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_manufectoring_date_request_heavy_vehical_manufacture_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveroperatorregistration',
            name='created_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subcontractorregistration',
            name='created_by',
            field=models.IntegerField(),
        ),
    ]
