# Generated by Django 4.1.5 on 2023-02-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_driveroperatorregistration_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heavyvehivalregistration',
            name='vehicle_image',
            field=models.FileField(upload_to='static/images/vehicles/1.jpg'),
        ),
    ]
